multiple temps

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -45,7 +45,7 @@ MAX=255
 
 function LoadConfig
 {
-	local fcvcount fcv
+	local fcvcount fcv numtemps tempcount mint maxt
 
 	echo "Loading configuration from $1 ..."
 	if [ ! -r "$1" ]
@@ -97,6 +97,8 @@ function LoadConfig
 			exit 1
 		fi
 
+		numtemps=$(echo $fcv |cut -d'=' -f2 |sed -e 's/+/ /g' |wc -w)
+
 		AFCPWM[$fcvcount]=$(echo $fcv |cut -d'=' -f1)
 		AFCTEMP[$fcvcount]=$(echo $fcv |cut -d'=' -f2)
 		AFCFAN[$fcvcount]=$(echo $FCFANS |sed -e 's/ /\n/g' |grep -E "${AFCPWM[$fcvcount]}" |cut -d'=' -f2)
@@ -112,12 +114,29 @@ function LoadConfig
 		[ -z "${AFCAVERAGE[$fcvcount]}" ] && AFCAVERAGE[$fcvcount]=1
 
 		# verify the validity of the settings
-		if [ "${AFCMINTEMP[$fcvcount]}" -ge "${AFCMAXTEMP[$fcvcount]}" ]
+		if [ "$numtemps" -ne $(echo ${AFCMINTEMP[$fcvcount]} |sed -e 's/+/ /g' |wc -w) ]
 		then
 			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
-			echo "MINTEMP must be less than MAXTEMP" >&2
+			echo "number of TEMPS must equal number of MINTEMPs" >&2
 			exit 1
 		fi
+		if [ "$numtemps" -ne $(echo ${AFCMAXTEMP[$fcvcount]} |sed -e 's/+/ /g' |wc -w) ]
+		then
+			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+			echo "number of TEMPS must equal number of MAXTEMPs" >&2
+			exit 1
+		fi
+		for tempcount in $(seq 1 $numtemps)
+		do
+			mint=$(echo ${AFCMINTEMP[$fcvcount]} |cut -d'+' -f $tempcount)
+			maxt=$(echo ${AFCMAXTEMP[$fcvcount]} |cut -d'+' -f $tempcount)
+			if [ "$mint" -ge "$maxt" ]
+			then
+				echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
+				echo "MINTEMP must be less than MAXTEMP" >&2
+				exit 1
+			fi
+		done
 		if [ "${AFCMAXPWM[$fcvcount]}" -gt 255 ]
 		then
 			echo "Error in configuration file (${AFCPWM[$fcvcount]}):" >&2
@@ -296,12 +315,15 @@ function CheckFiles
 	let fcvcount=0
 	while (( $fcvcount < ${#AFCTEMP[@]} )) # go through all temp inputs
 	do
-		tsen=${AFCTEMP[$fcvcount]}
-		if [ ! -r $tsen ]
-		then
-			echo "Error: file $tsen doesn't exist or isn't readable" >&2
-			outdated=1
-		fi
+		# A given PWM output can have several tsen inputs
+		for tsen in $(echo ${AFCTEMP[$fcvcount]} | sed -e 's/+/ /')
+		do
+			if [ ! -r $tsen ]
+			then
+				echo "Error: file $tsen doesn't exist or isn't readable" >&2
+				outdated=1
+			fi
+		done
 		let fcvcount=$fcvcount+1
 	done
 
@@ -521,10 +543,11 @@ trap 'restorefans 1' SIGHUP SIGINT
 # main function
 function UpdateFanSpeeds
 {
-	local fcvcount
+	local fcvcount numtemps tempcount
 	local pwmo tsens fan mint maxt minsa minso minpwm maxpwm
 	local tval tlastval pwmpval fanval min_fanval one_fan one_fanval
-	local -i pwmval
+	local numtemps tempcount tsen
+	local -i pwmval pwmvaltemp
 
 	let fcvcount=0
 	while (( $fcvcount < ${#AFCPWM[@]} )) # go through all pwm outputs
@@ -533,20 +556,13 @@ function UpdateFanSpeeds
 		pwmo=${AFCPWM[$fcvcount]}
 		tsens=${AFCTEMP[$fcvcount]}
 		fan=${AFCFAN[$fcvcount]}
-		let mint="${AFCMINTEMP[$fcvcount]}*1000"
-		let maxt="${AFCMAXTEMP[$fcvcount]}*1000"
 		minsa=${AFCMINSTART[$fcvcount]}
 		minso=${AFCMINSTOP[$fcvcount]}
 		minpwm=${AFCMINPWM[$fcvcount]}
 		maxpwm=${AFCMAXPWM[$fcvcount]}
 		avg=${AFCAVERAGE[$fcvcount]}
-
-		read tlastval < ${tsens}
-		if [ $? -ne 0 ]
-		then
-			echo "Error reading temperature from $DIR/$tsens"
-			restorefans 1
-		fi
+		numtemps=$(echo $tsens |sed -e 's/+/ /g' |wc -w)
+		pwmval=0
 
 		read pwmpval < ${pwmo}
 		if [ $? -ne 0 ]
@@ -554,20 +570,6 @@ function UpdateFanSpeeds
 			echo "Error reading PWM value from $DIR/$pwmo"
 			restorefans 1
 		fi
-
-		# copy PREVIOUSTEMP_$fcvcount array to prevtemp
-		declare -a 'prevtemp=(${'"PREVIOUSTEMP_$fcvcount"'[@]})'
-		# add new element to the end of the array
-		prevtemp+=($tlastval)
-		# if needed, remove the first element of the array
-		if [ "${#prevtemp[@]}" -gt $avg ]
-		then
-			prevtemp=("${prevtemp[@]:1}")
-		fi
-		# calculate the average value of all elements
-		tval=$(( ( ${prevtemp[@]/%/+}0 ) / ${#prevtemp[@]} ))
-		# copy prevtemp back to PREVIOUSTEMP_$fcvcount
-		eval "PREVIOUSTEMP_$fcvcount=(\"${prevtemp[@]}\")"
 
 		# If fanspeed-sensor output shall be used, do it
 		if [[ -n ${fan} ]]
@@ -601,6 +603,48 @@ function UpdateFanSpeeds
 			min_fanval=1  # set it to a non zero value, so the rest of the script still works
 		fi
 
+		for tempcount in $(seq 1 $numtemps)
+		do
+			tsen=$(echo $tsens |cut -d'+' -f $tempcount)
+			let mint="$(echo ${AFCMINTEMP[$fcvcount]} |cut -d'+' -f $tempcount)*1000"
+			let maxt="$(echo ${AFCMAXTEMP[$fcvcount]} |cut -d'+' -f $tempcount)*1000"
+
+			read tlastval < ${tsen}
+			if [ $? -ne 0 ]
+			then
+				echo "Error reading temperature from $DIR/$tsen"
+				restorefans 1
+			fi
+
+			# copy PREVIOUSTEMP_$fcvcount_$tempcount array to prevtemp
+			declare -a 'prevtemp=(${'"PREVIOUSTEMP_${fcvcount}_$tempcount"'[@]})'
+			# add new element to the end of the array
+			prevtemp+=($tlastval)
+			# if needed, remove the first element of the array
+			if [ "${#prevtemp[@]}" -gt $avg ]
+			then
+				prevtemp=("${prevtemp[@]:1}")
+			fi
+			# calculate the average value of all elements
+			tval=$(( ( ${prevtemp[@]/%/+}0 ) / ${#prevtemp[@]} ))
+			# copy prevtemp back to PREVIOUSTEMP_$fcvcount_$tempcount
+			eval "PREVIOUSTEMP_${fcvcount}_$tempcount=(\"${prevtemp[@]}\")"
+
+			if (( $tval <= $mint ))
+			  then pwmvaltemp=$minpwm # below min temp, use defined min pwm
+			elif (( $tval >= $maxt ))
+			  then pwmvaltemp=$maxpwm # over max temp, use defined max pwm
+			else
+			  # calculate the new value from temperature and settings
+			  pwmvaltemp="(${tval}-${mint})*(${maxpwm}-${minso})/(${maxt}-${mint})+${minso}"
+			fi
+			if [ $pwmvaltemp -ge $pwmval ]
+			then
+				pwmval=$pwmvaltemp
+			fi
+
+		done
+
 		# debug info
 		if [ "$DEBUG" != "" ]
 		then
@@ -621,20 +665,12 @@ function UpdateFanSpeeds
 			echo "min_fanval=$min_fanval"
 		fi
 
-		if (( $tval <= $mint ))
-		  then pwmval=$minpwm # below min temp, use defined min pwm
-		elif (( $tval >= $maxt ))
-		  then pwmval=$maxpwm # over max temp, use defined max pwm
-		else
-		  # calculate the new value from temperature and settings
-		  pwmval="(${tval}-${mint})*(${maxpwm}-${minso})/(${maxt}-${mint})+${minso}"
-		  if [ $pwmpval -eq 0 -o $min_fanval -eq 0 ]
-		  then # if fan was stopped start it using a safe value
-		  	echo $minsa > $pwmo
-			# Sleep while still handling signals
-			sleep 1 &
-			wait
-		  fi
+		if [ $pwmpval -eq 0 -o $min_fanval -eq 0 ] && [ $pwmval -gt 0 ]
+		then # if fan was stopped start it using a safe value
+			echo $minsa > $pwmo
+		      # Sleep while still handling signals
+		      sleep 1 &
+		      wait
 		fi
 		echo $pwmval > $pwmo # write new value to pwm output
 		if [ $? -ne 0 ]
